main:
  - name: Overview
    url: /#overview
    weight: 10
  - name: Game Flow
    url: /#game-flow
    weight: 20
  - name: Voice Command
    url: /#voice-command
    weight: 30
  - name: Collapse Effect
    url: /#collapse-effect
    weight: 40
  - name: Team
    url: /#team
    weight: 50

sidebar:
  - identifier: more
    name: Quick Links
    params:
      type: separator
    weight: 1
  - identifier: sourceRepo
    name: Source Repository
    url: https://github.com/ZYiyou/Jenga-Robot-in-VR-Display-site
    weight: 2
  - identifier: projectPage
    name: Project Overview
    pageRef: /project
    weight: 3
