main:
  - name: Home
    url: /
    weight: 10
  - name: Project
    url: /project/
    weight: 20
  - name: Architecture
    url: /architecture/
    weight: 30
  - name: Demo
    url: /demo/
    weight: 40
  - name: Engineering Challenges
    url: /challenges/
    weight: 50
  - name: Testing & Reflection
    url: /Testing/
    weight: 60
  - name: Team
    url: /team/
    weight: 70
  - name: Slides
    url: /slides/
    weight: 80
  - name: Reports
    url: /reports/
    weight: 90

sidebar:
  - identifier: more
    name: Need More?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: Community
    pageRef: /community
    weight: 2
  - identifier: projectRepo
    name: Project Repository
    url: https://github.com/ZYiyou/Jenga-Robot-in-VR-Display-site
    weight: 3
